entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  file:
    directory: /etc/traefik/dynamic/
    watch: true

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  myresolver:
    acme:
      email: rbarannik@sfedu.ru
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

accessLog: {}