http:
  routers:
    auth:
      rule: "PathPrefix(`/auth`)"
      service: auth
      middlewares:
        - "cors"
        - "admin-stripprefix"

  middlewares:
    admin-stripprefix:
      stripPrefix:
        prefixes:
        - "/auth"

  services:
    auth:
      loadBalancer:
        servers:
        - url: http://auth:3000/